[pytest]
filterwarnings =
    ignore:New instance .* conflicts with persistent instance:sqlalchemy.exc.SAWarning
    ignore::sqlalchemy.exc.SAWarning
pythonpath = C:\Projects\VKinder
testpaths = tests
markers =
    slow: Тесты, которые выполняются долго
    integration: Интеграционные тесты
    unit: Модульные тесты